on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd                                                # v6                                                # unpinned
      - uses: actions/setup-python@v5                                            # unpinned
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608          # outdated, no comment
      - uses: actions/setup-node@v4                                              # unpinned
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd         # v6.0.2 - correct, should be left alone
