on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4                                                # unpinned
      - uses: actions/setup-python@v5                                            # unpinned
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608          # outdated, no comment
      - uses: actions/setup-node@v4                                              # unpinned
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5         # v4.3.1 - correct, should be left alone
